### ISSUE TITLE
Why is the search accuracy on the CIFAR-10 dataset only 89% accuracy?

### ISSUE THREAD

**Issue by leidaguo** [khanrc/pt.darts#10]
Thank you for providing very good code. I executed search.py on multiple gpus, and the final result was only 89% accurate. Why? Need to continue augment.py to get 97% accuracy? Thank you

**Comment by twmht** [comment]
@leidaguo 

why you closes this? Did you find the answer?

**Comment by leidaguo** [comment]
@twmht Next run augment
