### ISSUE TITLE
Augment

### ISSUE THREAD

**Issue by TianMingChen** [khanrc/pt.darts#5]
请问，Augment是用来做什么的?

**Comment by khanrc** [comment]
Please write in English.

**Comment by TianMingChen** [comment]
what's the use of Augment?

**Comment by TianMingChen** [comment]
> Please write in English.

what's the use of Augment?

**Comment by khanrc** [comment]
After the search phase, you should make large network by stacking the found cell and should train it with more various training techniques. This is the augment phase.

**Comment by TianMingChen** [comment]
> After the search phase, you should make large network by stacking the found cell and should train it with more various training techniques. This is the augment phase.
Ok,thank you!

**Comment by TianMingChen** [comment]
ok,thank you!

**Comment by TianMingChen** [comment]
> After the search phase, you should make large network by stacking the found cell and should train it with more various training techniques. This is the augment phase.

ok,thank you!
